import { Product, Event } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Charizard ex - Obsidian Flames',
    category: 'pokemon',
    type: 'raw-single',
    set: 'Obsidian Flames',
    cardNumber: '125/197',
    condition: 'Near Mint',
    language: 'English',
    price: 34.99,
    quantity: 3,
    image: '/images/placeholder-card.png',
    featured: true,
    description: 'Near Mint Charizard ex from Obsidian Flames. One of the hottest cards in the set.',
    marketPrice: 39.99,
  },
  {
    id: 'p2',
    name: 'Pikachu VMAX - Crown Zenith',
    category: 'pokemon',
    type: 'raw-single',
    set: 'Crown Zenith',
    cardNumber: 'GG49/GG70',
    condition: 'Near Mint',
    language: 'English',
    price: 24.99,
    quantity: 5,
    image: '/images/placeholder-card.png',
    featured: true,
    description: 'Near Mint Pikachu VMAX Galarian Gallery from Crown Zenith.',
    marketPrice: 28.00,
  },
  {
    id: 'p3',
    name: 'PSA 10 Charizard - Base Set Shadowless',
    category: 'graded-slabs',
    type: 'graded-slab',
    set: 'Base Set Shadowless',
    grade: '10',
    certNumber: '12345678',
    gradingCompany: 'PSA',
    price: 4999.99,
    quantity: 1,
    image: '/images/placeholder-slab.png',
    featured: true,
    description: 'PSA 10 Base Set Shadowless Charizard. The holy grail of Pokémon cards.',
    marketPrice: 5500.00,
  },
  {
    id: 'p4',
    name: 'Scarlet & Violet Booster Box',
    category: 'sealed-products',
    type: 'sealed-product',
    productType: 'Booster Box',
    releaseDate: '2023-03-31',
    price: 139.99,
    quantity: 8,
    image: '/images/placeholder-box.png',
    featured: true,
    description: 'Factory sealed Scarlet & Violet booster box. 36 packs per box.',
    marketPrice: 149.99,
  },
  {
    id: 'p5',
    name: 'Monkey D. Luffy - OP01-001 Alt Art',
    category: 'one-piece',
    type: 'raw-single',
    set: 'Romance Dawn',
    cardNumber: 'OP01-001',
    condition: 'Near Mint',
    language: 'English',
    price: 89.99,
    quantity: 2,
    image: '/images/placeholder-card.png',
    featured: true,
    description: 'Alternate art Luffy leader from the Romance Dawn set.',
    marketPrice: 99.99,
  },
  {
    id: 'p6',
    name: 'Patrick Mahomes Rookie Prizm PSA 10',
    category: 'sports-cards',
    type: 'graded-slab',
    set: '2017 Prizm',
    grade: '10',
    certNumber: '87654321',
    gradingCompany: 'PSA',
    price: 899.99,
    quantity: 1,
    image: '/images/placeholder-slab.png',
    featured: true,
    description: 'PSA 10 Patrick Mahomes rookie Prizm. Sharp corners, perfect centering.',
    marketPrice: 950.00,
  },
  {
    id: 'p7',
    name: 'Paldean Fates Elite Trainer Box',
    category: 'sealed-products',
    type: 'sealed-product',
    productType: 'ETB',
    releaseDate: '2024-01-26',
    price: 59.99,
    quantity: 12,
    image: '/images/placeholder-box.png',
    featured: true,
    description: 'Paldean Fates ETB with shiny Pokémon throughout.',
    marketPrice: 64.99,
  },
  {
    id: 'p8',
    name: 'Umbreon VMAX Alt Art - Evolving Skies',
    category: 'pokemon',
    type: 'raw-single',
    set: 'Evolving Skies',
    cardNumber: '215/203',
    condition: 'Near Mint',
    language: 'English',
    price: 149.99,
    quantity: 1,
    image: '/images/placeholder-card.png',
    featured: true,
    description: 'The most popular alternate art VMAX from Evolving Skies.',
    marketPrice: 160.00,
  },
  {
    id: 'p9',
    name: 'One Piece Romance Dawn Booster Box',
    category: 'one-piece',
    type: 'sealed-product',
    productType: 'Booster Box',
    releaseDate: '2022-12-02',
    price: 89.99,
    quantity: 4,
    image: '/images/placeholder-box.png',
    featured: false,
    description: 'Factory sealed Romance Dawn booster box. 24 packs.',
    marketPrice: 99.99,
  },
  {
    id: 'p10',
    name: 'BGS 9.5 Mike Trout Rookie - Topps Update',
    category: 'sports-cards',
    type: 'graded-slab',
    set: '2009 Topps Update',
    grade: '9.5',
    certNumber: '11223344',
    gradingCompany: 'BGS',
    price: 1299.99,
    quantity: 1,
    image: '/images/placeholder-slab.png',
    featured: false,
    description: 'BGS 9.5 Mike Trout rookie card. Quad 9.5 subgrades.',
    marketPrice: 1400.00,
  },
  {
    id: 'p11',
    name: 'Mew ex - 151 Collection',
    category: 'pokemon',
    type: 'raw-single',
    set: 'Pokemon 151',
    cardNumber: '205/165',
    condition: 'Near Mint',
    language: 'English',
    price: 44.99,
    quantity: 6,
    image: '/images/placeholder-card.png',
    featured: false,
    description: 'Mew ex Special Illustration Rare from Pokemon 151.',
    marketPrice: 49.99,
  },
  {
    id: 'p12',
    name: 'Pokémon 151 Ultra Premium Collection',
    category: 'sealed-products',
    type: 'sealed-product',
    productType: 'Collection Box',
    releaseDate: '2023-10-06',
    price: 119.99,
    quantity: 3,
    image: '/images/placeholder-box.png',
    featured: false,
    description: 'Pokemon 151 Ultra Premium Collection featuring Mew.',
    marketPrice: 129.99,
  },
];

export const events: Event[] = [
  {
    id: 'e1',
    name: 'Collect-A-Con Dallas',
    date: '2026-07-12',
    location: 'Kay Bailey Hutchison Convention Center',
    city: 'Dallas, TX',
    time: '9:00 AM - 6:00 PM',
    boothInfo: 'Booth #247 - Hall B',
    description: 'One of the largest trading card conventions in Texas. Find us at Booth #247 in Hall B with our full inventory of singles, slabs, and sealed products.',
    type: 'card-show',
  },
  {
    id: 'e2',
    name: 'Wichita Falls Card Show',
    date: '2026-06-28',
    location: 'MPEC - Multipurpose Events Center',
    city: 'Wichita Falls, TX',
    time: '10:00 AM - 4:00 PM',
    boothInfo: 'Main Floor - Table 12',
    description: 'Local card show right here in Wichita Falls. Shop Pokémon, sports cards, One Piece, and more. Great deals on singles and sealed products.',
    type: 'local-event',
  },
  {
    id: 'e3',
    name: 'Regional Pokémon League Cup',
    date: '2026-07-19',
    location: 'Sike\'s Senter Mall',
    city: 'Wichita Falls, TX',
    time: '11:00 AM - 5:00 PM',
    boothInfo: 'Vendor Area - Table 3',
    description: 'Official Pokémon League Cup event. We\'ll be vending with singles, sealed products, and accessories perfect for competitive players.',
    type: 'league-cup',
  },
  {
    id: 'e4',
    name: 'North Texas Sports Card Expo',
    date: '2026-08-02',
    location: 'Lone Star Park',
    city: 'Grand Prairie, TX',
    time: '9:00 AM - 5:00 PM',
    boothInfo: 'Booth #88',
    description: 'Major sports card expo featuring dealers from across Texas and Oklahoma. We\'ll have our full sports card inventory plus Pokémon and One Piece.',
    type: 'expo',
  },
];

export const categories = [
  {
    id: 'pokemon',
    name: 'Pokémon',
    description: 'Browse singles, sealed products, slabs, and collectibles.',
    icon: '⚡',
    color: 'from-yellow-600 to-yellow-800',
  },
  {
    id: 'one-piece',
    name: 'One Piece',
    description: 'Shop sealed products, singles, and graded cards.',
    icon: '⚓',
    color: 'from-red-700 to-red-900',
  },
  {
    id: 'sports-cards',
    name: 'Sports Cards',
    description: 'Explore rookie cards, slabs, autos, and collectibles.',
    icon: '🏆',
    color: 'from-blue-700 to-blue-900',
  },
  {
    id: 'graded-slabs',
    name: 'Graded Slabs',
    description: 'Premium graded inventory from PSA, BGS, and CGC.',
    icon: '🏅',
    color: 'from-purple-700 to-purple-900',
  },
  {
    id: 'sealed-products',
    name: 'Sealed Products',
    description: 'Booster boxes, ETBs, and sealed collectibles.',
    icon: '📦',
    color: 'from-green-700 to-green-900',
  },
  {
    id: 'collections-wanted',
    name: 'Collections Wanted',
    description: 'Sell your collection — we buy singles, slabs, and bulk.',
    icon: '💰',
    color: 'from-amber-700 to-amber-900',
  },
];
